version: '3.4'

services:
  poc.api:
    image: ${DOCKER_REGISTRY-}pocapi
    build:
      context: .
      dockerfile: POC.API/Dockerfile
    container_name: web_api_bank
    ports:
      - "5001:80"
    depends_on:
     - sqldb

  poc_country.api:
    image: ${DOCKER_REGISTRY-}poccountryapi
    build:
      context: .
      dockerfile: POC_Country.API/Dockerfile
    container_name: web_api_country
    ports:
      - "5002:80"
    depends_on:
      - sqldb

  sqldb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_db
    ports:
      - "1433:1433"

    environment:
      SA_PASSWORD: "poc123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express

